### ISSUE TITLE
App icon is misaligned

### ISSUE THREAD

**Issue by tomasz-oponowicz** [bitstower/markets#2]
## Test case

1. Install app on Mobian
1. Open the dashboard

### Expected
The icon should be aligned.

![home](https://user-images.githubusercontent.com/615940/88475301-e5426380-cf2e-11ea-80eb-ee8ddc0de8df.png)

**Comment by tomasz-oponowicz** [comment]
@gusbemacbe Can you take a look? I think the bottom padding is wrong.

**Comment by gusbemacbe** [comment]
Yes, I could see, I will analyse the icon. Does Adwaita icons theme has Power Apply's icon?

**Comment by tomasz-oponowicz** [comment]
@gusbemacbe 

Not sure, but you can compare it with gnome-record or gnome-screenshot instead. They have the same shape.

https://gitlab.gnome.org/GNOME/gnome-screenshot/-/blob/master/data/icons/hicolor/scalable/apps/org.gnome.Screenshot.svg
https://gitlab.gnome.org/GNOME/gnome-sound-recorder/-/blob/master/data/icons/org.gnome.SoundRecorder.svg

**Comment by gusbemacbe** [comment]
Done, @tomasz-oponowicz.

**Comment by tomasz-oponowicz** [comment]
Fixed in 0.3.0
