### ISSUE TITLE
Refine app icon?

### ISSUE THREAD

**Issue by bertob** [bitstower/markets#36]
The current icon isn't too bad, but I feel like it could be nicer particularly with regard to colors, the red/green combination feels a bit meh. I'd be happy to help explore some alternatives if you're interested.

As a quick experiment to get nicer colors I tried something with multiple stocks and a dark screen:

![image](https://user-images.githubusercontent.com/1908896/97003177-5815a780-153b-11eb-9cf0-38bdea92b8e4.png)

**Comment by bertob** [comment]
Another experiment with just a single color:

![image](https://user-images.githubusercontent.com/1908896/97004422-5b119780-153d-11eb-8f8e-a47f8146c17a.png)

**Comment by tomasz-oponowicz** [comment]
@bertob Thank you for taking the time! Wow, obviously both icons look great :) I like the second one a little bit more, I think it's more stylish.

**Comment by bertob** [comment]
Cool! Want me to open an MR?

Color variation on the second one:

![image](https://user-images.githubusercontent.com/1908896/97119995-60750a80-1714-11eb-93e5-5583115c3fa3.png)

**Comment by tomasz-oponowicz** [comment]
> Cool! Want me to open an MR?

Yes, please.

> Color variation on the second one:

IMHO it's even better :) Green represents profits. Thus it has pleasent / possitive meaning.
