### ISSUE TITLE
Support for stable libhandy? 

### ISSUE THREAD

**Issue by Ferenc-** [bitstower/markets#38]
Is there a plan to support the stable libhandy-1-0?
I see that the current code uses 
Hdy.Dialog which has been dropped from libhandy, the way I understand Hdy.Deck meant to be used instead.
Is there anything other known obstacle?

**Comment by tomasz-oponowicz** [comment]
> Is there a plan to support the stable libhandy-1-0?
Yes. there is a plan to support libhandy1 in the near future.

> Is there anything other known obstacle?
Honestly. I don't know. I haven't checked libhandy1 yet.

**Comment by tomasz-oponowicz** [comment]
Done.
