### ISSUE TITLE
Emphasize stock name

### ISSUE THREAD

**Issue by jimmac** [bitstower/markets#46]
*Markets* emphasizes the stock price as the major element. The name of the stock/identifier is lost in the amount of data presented. I would personally de-emphasize the market price to be at the level as the gain/loss and boost the visual emphasis of the name.

**Comment by tomasz-oponowicz** [comment]
Sorry for the late reply. I did a quick prototype based on your suggestion. Is it aligned with your vision?

![Screenshot from 2020-12-26 14-29-38](https://user-images.githubusercontent.com/615940/103152278-d20a1d00-4786-11eb-8b3e-ee43a2f00478.png)

**Comment by jimmac** [comment]
That looks much better. I'd also group the stock price and the change together on the right, having easy spatial separation of the kind/price on the horizontal axis.

**Comment by tomasz-oponowicz** [comment]
I like your idea. Though the title would push price/change when too long. Maybe an ellipsized label would help. What do you think? Can you prepare a mockup?

**Comment by tomasz-oponowicz** [comment]
I did a quick mockup:

![Screenshot from 2021-01-03 14-11-24](https://user-images.githubusercontent.com/615940/103479390-a5c94e80-4dcd-11eb-9de4-e390a1374aa3.png)

What do you think? Do you have other suggestions?

**Comment by jimmac** [comment]
That looks exactly how I imaged, a nice separation of kind and pricing.

**Comment by tomasz-oponowicz** [comment]
Thanks for suggestions. Resolved. Closing...
