### ISSUE TITLE
Can't reorder list elements

### ISSUE THREAD

**Issue by hadess** [bitstower/markets#6]
The latest Flathub version from this morning (0.1.0) can't reorder elements, which makes organisation more complicated.

**Comment by Nokia808** [comment]
Yes. I agree with this. I suggested to add options to move up / move down for selected items.

**Comment by hadess** [comment]
GNOME applications usually use handles. See the “Search” panel in the GNOME Settings for an example (this one also uses move up/down menu items behind a 3 dots button)

**Comment by tomasz-oponowicz** [comment]
I agree, reordering would be useful.

**Comment by tomasz-oponowicz** [comment]
Reordering example:

![reordering](https://user-images.githubusercontent.com/615940/89653430-5edf3780-d8c7-11ea-9211-e58239595cba.png)

**Comment by tomasz-oponowicz** [comment]
An entry should have handle and checkbox at the beginning. Move up/down menu isn't needed. For example:

```
:: [✔] Tesla
```

**Comment by hadess** [comment]
> Move up/down menu isn't needed.

It's needed for accessibility purposes.

**Comment by tomasz-oponowicz** [comment]
Thanks for pointing that out. I'm afraid we don't have enough space on mobile to have extra _move up/down_ menu.
