### ISSUE TITLE
Icon doesn't show in Alt Tab switcher

### ISSUE THREAD

**Issue by JaneSmith** [bitstower/markets#63]
I originally thought the app just didn't have an icon... but when I searched the issue tracker, I found issues discussing putting together an icon, and indeed it does have an icon in GNOME Software and in the Apps Grid. However, it doesn't have its icon when using the Alt+Tab switcher, and doesn't have its icon in the Activities view (with the WindowPreview extension and I guess the GNOME 40 update too). It just uses the generic blue diamond icon.

The app also uses a less friendly display name in the Alt+Tab switcher, as well as on the Top Bar. It shows "bitstower-markets" in the Top Bar and "bitstower-mar..." in the Alt+Tab switcher, instead of the name "Markets".

Testing on Fedora Silverblue with the Flathub package.

## Test case
1. Press Alt+Tab.

### Actual
"Markets" should be listed with the appropriate icon.

### Expected
"bitstower-mar..." is listed with a generic application icon.

**Comment by tomasz-oponowicz** [comment]
I have the latest version of Markets from Flathub and:

* There is a proper icon in the Alt + Tab switcher and the Activities view
* There is _Markets_ in the Alt + Tab switcher

Can you double check if you have the similar issue with other apps from Flathub?
Do you use a custom icon theme?

My env:
* Flatpak 1.10.1
* Arch

**Comment by JaneSmith** [comment]
I don't have the issue with any other apps, and I do not use a custom icon theme.

That said, I'm no longer encountering this issue. It works fine now... so I'm not sure what the cause was. I suppose it should be chalked up to a "random glitch" and the issue closed? Sorry for the time wasting. I'll try to keep an eye out to see if it happens again.

**Comment by tomasz-oponowicz** [comment]
Sounds good. Closing. Feel free to reopen if needed.
