### ISSUE TITLE
Indices shouldn't have currency

### ISSUE THREAD

**Issue by SuborbitalPigeon** [bitstower/markets#70]
## Test case

1. __Enter steps__

Add a market index (^FTSE, ^GSPC for example).

### Actual
__Enter actual output__

Note that the number has a currency, but indices are dimensionless.

### Expected
__Enter expected output__

Indices shouldn't have units.

It appears from the Yahoo finance website that the data which is passed to the program probably has a currency unit. However, the symbols for indices always start with a '^', so I suppose the currency could be ignored if this is the case.

**Comment by elliotwutingfeng** [comment]
I think this can be closed now?

**Comment by tomasz-oponowicz** [comment]
Correct. Closing...
