### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by alyssais** [bitstower/markets#72]
Hi! I'm looking into packaging Markets for [Nixpkgs](https://nixos.org).  I wasn't able to tell at a glance whether the license for this project is GPL 3 **only**, or GPL 3 **or later**.  Upon further investigation, I found that the Flatpak metadata said "GPL-3.0-or-later", but it would be great if this could be mentioned somewhere more obvious (like the README), because in my experience as a packager license metadata in Flatpak, npm, etc. configurations is often out of date / not what the author intended.

Thanks!

**Comment by tomasz-oponowicz** [comment]
@alyssais Sorry for the late reply, I was off for some time. Thanks for looking into packaging Markets for Nixpkgs. 

The license is "GPL-3.0" and it is mentioned here:

https://github.com/bitstower/markets/blob/master/COPYING

...I will fix Flatpak metadata by changing it to "GPL-3.0".

**Comment by tomasz-oponowicz** [comment]
Done.

**Comment by tomasz-oponowicz** [comment]
I've read about the differences between those two and I changed my mind. Let's make it _GPL-3.0-or-later_. I added a note in the REAMDE and Flatpak metadata contains _GPL-3.0-or-later_. It should be clear now.

**Comment by alyssais** [comment]
Thanks!
