### ISSUE TITLE
Add the Basque (eu.po) translation I made in Weblate

### ISSUE THREAD

**Issue by IngrownMink4** [bitstower/markets#77]
Hey, [I added the Basque translation of your project in Weblate some time ago](https://hosted.weblate.org/projects/markets/markets/eu/) and I have seen that it is not yet included in the project. I would be happy if you could add it (I know there are not many people who speak it but the more languages the better!)

![firefox_KIPU6jxumO](https://user-images.githubusercontent.com/25466522/134692526-2b9ef0f0-5853-4c43-be93-aeb270089654.png)

P.S. Thank you for developing the app :)

**Comment by tomasz-oponowicz** [comment]
Thank you for your contribution. I've just merged the Basque translation.

**Comment by IngrownMink4** [comment]
Thanks! @tomasz-oponowicz
