### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [bitstower/markets#78]
The current summary "A stock, currency and cryptocurrency tracker" isn't great (too long, too much detail, not very engaging).

I'd suggest something like "Keep track of your investments", or "Keep track of your portolio".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by tomasz-oponowicz** [comment]
hey @bertob, thank you for your suggestion. done
