### ISSUE TITLE
(Feature Request) Snap/AppImage version of markets

### ISSUE THREAD

**Issue by dtantono** [bitstower/markets#80]
Hi
I find this app is quite interesting. Is this possible to have this app on Appimage/Snap?

**Comment by Tachi107** [comment]
@dtantono don't know if this can help, but Markets is already available in an universal packaging format (flatpak) on Flathub: https://flathub.org/apps/details/com.bitstower.Markets

**Comment by tomasz-oponowicz** [comment]
I agree with @Tachi107, the Flatpak package should be sufficient. However if you have resources to maintain Appimage/Snap package, then feel free create one.
