### ISSUE TITLE
Update translations from Weblate

### ISSUE THREAD

**Issue by milotype** [bitstower/markets#87]
I've translated Croatian and made some minor changes in the German translation file.

I'm not a programmer, but I think there is a way to update translations from Weblate on a regular basis or as soon as there are changes in Weblate's translation files. That would help keeping translations up-to-date.

The above is just a suggestion :-)

**Comment by tomasz-oponowicz** [comment]
I've just merged and released your changes. Thank you for your contribution.

With regards to updating translations automatically, I prefer doing this manually ;)
